"use client";
import { ChangeEvent, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import type { ContentEntry } from "@/lib/content";

const empty:any={id:"",title:"",subtitle:"",body:"",image_url:null,actions:[],layout_variant:"text-left",position:999,published:true};
function safe(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^\w.-]+/g,"-");}
export default function AdminContentManager({section,label,initialEntries}:{section:ContentEntry["section"];label:string;initialEntries:ContentEntry[]}){
 const [entries,setEntries]=useState(initialEntries); const [id,setId]=useState(initialEntries[0]?.id||"new"); const entry=useMemo(()=>id==="new"?{...empty}:entries.find(e=>e.id===id)||{...empty},[id,entries]); const [draft,setDraft]=useState<any>(entry); const [busy,setBusy]=useState(false); const [status,setStatus]=useState("");
 function choose(value:string){setId(value);setDraft(value==="new"?{...empty}:{...(entries.find(e=>e.id===value)||empty)});setStatus("")}
 function f(k:string,v:any){setDraft((d:any)=>({...d,[k]:v}))}
 function action(index:number,key:"label"|"url",value:string){const actions=[...(draft.actions||[])]; while(actions.length<=index)actions.push({label:"",url:""});actions[index]={...actions[index],[key]:value};f("actions",actions)}
 async function save(){setBusy(true);try{const supabase=createClient(); const payload={section,title:draft.title,subtitle:draft.subtitle||null,body:draft.body||null,image_url:draft.image_url||null,actions:(draft.actions||[]).filter((a:any)=>a.label&&a.url),layout_variant:draft.layout_variant||null,position:Number(draft.position)||0,published:!!draft.published,updated_at:new Date().toISOString()};let row:any;if(draft.id){const {data,error}=await supabase.from("content_entries").update(payload).eq("id",draft.id).select("*").single();if(error)throw error;row=data;setEntries(es=>es.map(e=>e.id===row.id?row:e));}else{const {data,error}=await supabase.from("content_entries").insert(payload).select("*").single();if(error)throw error;row=data;setEntries(es=>[...es,row]);setId(row.id);}setDraft(row);setStatus("Guardado correctamente.");}catch(e:any){setStatus(`Error: ${e.message||e}`)}finally{setBusy(false)}}
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const supabase=createClient();const p=`${section}/${Date.now()}-${safe(file.name)}`;const {error}=await supabase.storage.from("site-content").upload(p,file,{contentType:file.type||undefined});if(error)throw error;f("image_url",supabase.storage.from("site-content").getPublicUrl(p).data.publicUrl);}catch(err:any){alert(err.message||err)}finally{setBusy(false);e.target.value=""}}
 return <div className="admin-project-layout"><aside className="admin-project-list"><button onClick={()=>choose("new")} className={id==="new"?"active":""}>+ Nuevo</button>{entries.map(e=><button key={e.id} onClick={()=>choose(e.id)} className={id===e.id?"active":""}>{e.title}<small>{e.published?"Publicado":"Borrador"}</small></button>)}</aside><section className="admin-card admin-editor"><div className="admin-editor-head"><h1>{label}</h1><button className="primary" onClick={save} disabled={busy}>Guardar</button></div>{status&&<p className="admin-status">{status}</p>}<div className="admin-form-grid"><label className="admin-field">Título<input value={draft.title||""} onChange={e=>f("title",e.target.value)}/></label><label className="admin-field">Subtítulo<input value={draft.subtitle||""} onChange={e=>f("subtitle",e.target.value)}/></label><label className="admin-field">Orden<input type="number" value={draft.position||0} onChange={e=>f("position",e.target.value)}/></label><label className="admin-field">Layout<select value={draft.layout_variant||"text-left"} onChange={e=>f("layout_variant",e.target.value)}><option value="text-left">Texto izquierda</option><option value="image-left">Imagen izquierda</option><option value="intro">Introducción</option><option value="person">Persona</option></select></label><label className="admin-field admin-field-wide">Texto<textarea value={draft.body||""} onChange={e=>f("body",e.target.value)}/></label></div><div className="admin-upload-box admin-upload-wide"><h3>Imagen</h3><p>Editorial: ideal 1600 px o más. Personas: retrato cuadrado 1200×1200 px.</p>{draft.image_url&&<img src={draft.image_url} alt=""/>}<input type="file" accept="image/*" onChange={upload}/></div><div className="admin-form-grid"><label className="admin-field">Botón 1<input placeholder="Ver publicación" value={draft.actions?.[0]?.label||""} onChange={e=>action(0,"label",e.target.value)}/></label><label className="admin-field">URL botón 1<input value={draft.actions?.[0]?.url||""} onChange={e=>action(0,"url",e.target.value)}/></label><label className="admin-field">Botón 2<input placeholder="Ver catálogo" value={draft.actions?.[1]?.label||""} onChange={e=>action(1,"label",e.target.value)}/></label><label className="admin-field">URL botón 2<input value={draft.actions?.[1]?.url||""} onChange={e=>action(1,"url",e.target.value)}/></label></div><label className="admin-check"><input type="checkbox" checked={!!draft.published} onChange={e=>f("published",e.target.checked)}/> Publicado</label></section></div>;
}
